data_dir: /data/bic-mac-data/train #CHANGE to your dataset path
num_workers: 2
output_dir: outputs

epochs: 250
learning_rate: 0.0003

patch_size: [192,192,192]
train_num_samples: 2 #Number of patches to sample per train subject
val_num_samples: 8 #Number of patches to sample per val subject
